# Generated by Django 5.1 on 2025-11-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sala', models.IntegerField()),
                ('tipo_sala', models.CharField(choices=[('Tradicional', 'Tradicional'), ('3D', '3D'), ('4DX', '4DX'), ('VIP', 'VIP'), ('IMAX', 'IMAX'), ('JUNIOR', 'Junior')], default='Tradicional', max_length=20)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Ocupada', 'Ocupada'), ('Desocupada', 'Desocupada'), ('En mantenimiento', 'En mantenimiento')], default='Desocupada', max_length=20)),
                ('fecha_ultimo_mantenimiento', models.DateField()),
                ('asientos_especiales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cine', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('numero_salas', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('formatos', models.CharField(choices=[('tradicional', 'Tradicional'), ('3D', '3D'), ('4DX', '4DX'), ('VIP', 'VIP'), ('IMAX', 'IMAX'), ('JUNIOR', 'Junior')], default='tradicional', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('sinopsis', models.TextField()),
                ('director', models.CharField(max_length=150)),
                ('salas', models.ManyToManyField(related_name='peliculas', to='app_Cinepolis.sala')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='app_Cinepolis.sucursal'),
        ),
    ]
