# Generated by Django 5.1 on 2025-11-12 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cinepolis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('puntos_cinepolis', models.IntegerField(default=0)),
                ('membresia_cinepolis', models.CharField(choices=[('Tradicional', 'Tradicional'), ('Premium', 'Premium'), ('Club CinépolisFan', 'Club Cinépolis Fan'), ('Club Cinépolis Fanático', 'Club Cinépolis Fanático'), ('Club Cinépolis Súper Fanático', 'Club Cinépolis Súper Fanático')], default='Tradicional', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('precio_boleto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idioma', models.CharField(choices=[('Español', 'Español'), ('Ingles', 'Inglés'), ('Subtitulada', 'Subtitulada')], default='Español', max_length=20)),
                ('estatus', models.CharField(choices=[('Programada', 'Programada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Programada', max_length=20)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='app_Cinepolis.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='app_Cinepolis.sala')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='app_Cinepolis.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_boletos', models.IntegerField()),
                ('precio_boleto_momento_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta de Credito', 'Tarjeta de Crédito'), ('Tarjeta de Debito', 'Tarjeta de Débito'), ('Efectivo', 'Efectivo'), ('Puntos Cinepolis', 'Puntos Cinépolis')], default='Tarjeta de Credito', max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='app_Cinepolis.cliente')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='app_Cinepolis.funcion')),
            ],
        ),
    ]
